Update NmApTe

diff --git a/NmApTe b/NmApTe
--- a/NmApTe
+++ b/NmApTe
@@ -138,14 +138,13 @@ do
   read scan
 done
 else
-scan="$2"
+   scan="$2"
 fi
 ## Check If Choice Exist OR Not..:)
-sc=
 if [ "$scan" -gt "31" ]
    then
-printf "\n\e[1;31m[!]\e[0;31m[ERROR] Of Your Choice[\e[1;33m$scan\e[0;31m] Does Not Exist In \e[1;32mMenu\e[1;31m !!!\n"
-    exit 1
+      printf "\n\e[1;31m[!]\e[0;31m[ERROR] Of Your Choice[\e[1;33m$scan\e[0;31m] Does Not Exist In \e[1;32mMenu\e[1;31m !!!\n"
+      exit 1
 fi
 ## Set TARGET..:)
 
@@ -158,7 +157,7 @@ do
   read target
 done
 else
-target="$1"
+   target="$1"
 fi
 ## Started..:)
 if [[ $scan == '1' ]]
