Update

diff --git a/NmApTe b/NmApTe
--- a/NmApTe
+++ b/NmApTe
@@ -115,6 +115,8 @@ printf '\e[0;34m\t[26]\e[1;34m     >  \e[1;36m  Full Port Scan (UDP/Very Slow)\n
 printf '\e[0;34m\t[27]\e[1;34m     >  \e[1;36m  Most Common Ports (TCP)\n'
 printf '\e[0;34m\t[28]\e[1;34m     >  \e[1;36m  Most Common Ports (UDP)\n'
 printf '\e[0;34m\t[29]\e[1;34m     >  \e[1;36m  Faster Regular Scan\n'
+printf '\e[0;34m\t[30]\e[1;34m     >  \e[1;36m  GET Site Map\n'
+printf '\e[0;34m\t[31]\e[1;34m     >  \e[1;36m  Cross-Site Scripting(XSS) Scan'
 printf '\n\e[1;0m==================\n\e[1;32m[#] \e[1;33mCtrl+C \e[1;31m For Exit -->\n\n '
 ## Done !
 # Usage Argv..:)
@@ -140,7 +142,7 @@ scan="$2"
 fi
 ## Check If Choice Exist OR Not..:)
 
-if [[ (($scan > 29 )) ]]
+if [[ (($scan > 31 )) ]]
    then
 printf "\n\e[1;31m[!]\e[0;31m[ERROR] Of Your Choice[\e[1;33m$scan\e[0;31m] Does Not Exist In \e[1;32mMenu\e[1;31m !!!\n"
     exit 1
@@ -775,9 +777,50 @@ elif [[ $scan == '29' ]]
 	    printf "\n\e[0;33m[!]\e[1;33m Please Check Your Network Connection \e[1;31m{OR}\e[1;33m This Target Server Not Found \e[1;31m!!!\n"
        fi
 
+elif [[ $scan == '30' ]]
+     then
+        ping -c 1 $target > /dev/null 2>&1
+        if [[ $? == "0" ]]
+          then
+             clear
+             sleep 0.20
+             printf "\n\e[1;35m==========>\e[1;36m Config\e[1;35m <=========="
+             sleep 0.15
+             printf "\n\e[1;32m[+]\e[1;35m TARGET:\e[1;31m $target\n"
+             sleep 0.15
+             printf "\e[1;32m[*]\e[1;35m Scan Type:\e[1;33m GET Site Map"
+             sleep 0.15
+             printf "\n\n\033[34m[*]\e[1;32m Scanning\033[1;31m......\n\e[1;37m"
+             nmap -Pn --script=http-sitemap-generator $target
+
+        else
+	    printf "\n\e[0;31m[!]\e[1;31m[ERROR]\e[1;33m I Can't Connect To TARGET[ \e[1;34m$target\e[1;33m ] \e[1;31m !!!"
+	    printf "\n\e[0;33m[!]\e[1;33m Please Check Your Network Connection \e[1;31m{OR}\e[1;33m This Target Server Not Found \e[1;31m!!!\n"
+        fi
+
+elif [[ $scan == '31' ]]
+     then
+        ping -c 1 $target  > /dev/null 2>&1
+        if [[ $? == "0" ]]
+          then
+             clear
+             sleep 0.20
+             printf "\n\e[1;35m==========>\e[1;36m Config\e[1;35m <=========="
+             sleep 0.15
+             printf "\n\e[1;32m[+]\e[1;35m TARGET:\e[1;31m $target\n"
+             sleep 0.15
+             printf "\e[1;32m[*]\e[1;35m Scan Type:\e[1;33m Cross-Site Scripting(XSS) Scanning"
+             sleep 0.15
+             printf "\n\n\033[34m[*]\e[1;32m Scanning\033[1;31m......\n\e[1;37m"
+              # Command :)
+             nmap -Pn --script=http-xssed $target
+
+        else
+	    printf "\n\e[0;31m[!]\e[1;31m[ERROR]\e[1;33m I Can't Connect To TARGET[ \e[1;34m$target\e[1;33m ] \e[1;31m !!!"
+	    printf "\n\e[0;33m[!]\e[1;33m Please Check Your Network Connection \e[1;31m{OR}\e[1;33m This Target Server Not Found \e[1;31m!!!\n"
+        fi
 
 fi
-
 ##############################################################
 ##################### 		     #########################
 #####################   END OF TOOL  #########################
